# CMake generated Testfile for 
# Source directory: /home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples
# Build directory: /home/chethana/ns-allinone-3.41/ns-3.41/cmake-cache/src/traffic-control/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-red-tests "ns3.41-red-tests-debug")
set_tests_properties(ctest-red-tests PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;1;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-red-vs-ared "ns3.41-red-vs-ared-debug")
set_tests_properties(ctest-red-vs-ared PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;12;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-adaptive-red-tests "ns3.41-adaptive-red-tests-debug")
set_tests_properties(ctest-adaptive-red-tests PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;23;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-pfifo-vs-red "ns3.41-pfifo-vs-red-debug")
set_tests_properties(ctest-pfifo-vs-red PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;34;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-codel-vs-pfifo-basic-test "ns3.41-codel-vs-pfifo-basic-test-debug")
set_tests_properties(ctest-codel-vs-pfifo-basic-test PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;45;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-codel-vs-pfifo-asymmetric "ns3.41-codel-vs-pfifo-asymmetric-debug")
set_tests_properties(ctest-codel-vs-pfifo-asymmetric PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;56;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-pie-example "ns3.41-pie-example-debug")
set_tests_properties(ctest-pie-example PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;68;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-fqcodel-l4s-example "ns3.41-fqcodel-l4s-example-debug")
set_tests_properties(ctest-fqcodel-l4s-example PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;79;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/traffic-control/examples/CMakeLists.txt;0;")
