# CMake generated Testfile for 
# Source directory: /home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng
# Build directory: /home/chethana/ns-allinone-3.41/ns-3.41/cmake-cache/src/aqua-sim-ng
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-broadcastMAC_example "ns3.41-broadcastMAC_example-debug")
set_tests_properties(ctest-broadcastMAC_example PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;161;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-floodtest "ns3.41-floodtest-debug")
set_tests_properties(ctest-floodtest PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;171;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-GOAL_string "ns3.41-GOAL_string-debug")
set_tests_properties(ctest-GOAL_string PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;181;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-ddos "ns3.41-ddos-debug")
set_tests_properties(ctest-ddos PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;191;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-bMAC "ns3.41-bMAC-debug")
set_tests_properties(ctest-bMAC PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;201;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-ND_example "ns3.41-ND_example-debug")
set_tests_properties(ctest-ND_example PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;212;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-VBF "ns3.41-VBF-debug")
set_tests_properties(ctest-VBF PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;222;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-FloodingMac "ns3.41-FloodingMac-debug")
set_tests_properties(ctest-FloodingMac PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;232;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-LibraGridTest "ns3.41-LibraGridTest-debug")
set_tests_properties(ctest-LibraGridTest PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;242;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-AlohaGridTest "ns3.41-AlohaGridTest-debug")
set_tests_properties(ctest-AlohaGridTest PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;252;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-SfamaGridTest "ns3.41-SfamaGridTest-debug")
set_tests_properties(ctest-SfamaGridTest PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;262;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-TrumacTest "ns3.41-TrumacTest-debug")
set_tests_properties(ctest-TrumacTest PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;272;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
add_test(ctest-JmacTest "ns3.41-JmacTest-debug")
set_tests_properties(ctest-JmacTest PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/src/aqua-sim-ng/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;282;build_lib_example;/home/chethana/ns-allinone-3.41/ns-3.41/src/aqua-sim-ng/CMakeLists.txt;0;")
