# CMake generated Testfile for 
# Source directory: /home/chethana/ns-allinone-3.41/ns-3.41/examples/socket
# Build directory: /home/chethana/ns-allinone-3.41/ns-3.41/cmake-cache/examples/socket
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-socket-bound-static-routing "ns3.41-socket-bound-static-routing-debug")
set_tests_properties(ctest-socket-bound-static-routing PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/examples/socket/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/examples/socket/CMakeLists.txt;1;build_example;/home/chethana/ns-allinone-3.41/ns-3.41/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-bound-tcp-static-routing "ns3.41-socket-bound-tcp-static-routing-debug")
set_tests_properties(ctest-socket-bound-tcp-static-routing PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/examples/socket/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/examples/socket/CMakeLists.txt;11;build_example;/home/chethana/ns-allinone-3.41/ns-3.41/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv4 "ns3.41-socket-options-ipv4-debug")
set_tests_properties(ctest-socket-options-ipv4 PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/examples/socket/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/examples/socket/CMakeLists.txt;22;build_example;/home/chethana/ns-allinone-3.41/ns-3.41/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv6 "ns3.41-socket-options-ipv6-debug")
set_tests_properties(ctest-socket-options-ipv6 PROPERTIES  WORKING_DIRECTORY "/home/chethana/ns-allinone-3.41/ns-3.41/build/examples/socket/" _BACKTRACE_TRIPLES "/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/chethana/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/chethana/ns-allinone-3.41/ns-3.41/examples/socket/CMakeLists.txt;32;build_example;/home/chethana/ns-allinone-3.41/ns-3.41/examples/socket/CMakeLists.txt;0;")
